# Generated by Django 4.2.1 on 2024-02-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_desc_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='detail',
        ),
    ]
