# Generated by Django 4.2.5 on 2024-06-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Address',
            new_name='address',
        ),
    ]
