# Generated by Django 4.2.1 on 2024-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_price_remove_cart_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
